### ISSUE TITLE
Fails with empty sound files

### ISSUE THREAD

**Issue by nuthatch** [hyperjeff/shuffle#1]
~/Documents/Coffitivity $ shuffle
   Filepath: paris-paradise.mp3
     Volume: ▁▂▃▄▅▆▇█     Duration: 0 of 0
2019-07-12 10:28:08.660 shuffle[75692:2109818] *** Assertion failure in -[NSDateComponentsFormatter stringFromTimeInterval:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1575.12/Foundation/String.subproj/NSDateComponentsFormatter.m:361
2019-07-12 10:28:08.662 shuffle[75692:2109818] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: isfinite(timeInterval) && !isnan(timeInterval)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff4808ccfd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7273ca17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff480a7a1a +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff4a346c85 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   Foundation                          0x00007fff4a3e29f9 -[NSDateComponentsFormatter stringFromTimeInterval:] + 369
	5   shuffle                             0x0000000108a3f338 shuffle + 66360
	6   shuffle                             0x0000000108a49796 shuffle + 108438
	7   shuffle                             0x0000000108a6c060 shuffle + 249952
	8   shuffle                             0x0000000108a373d0 shuffle + 33744
	9   libdispatch.dylib                   0x00007fff73ebc5f8 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x00007fff73ebd63d _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00007fff73ec868d _dispatch_main_queue_callback_4CF + 1135
	12  CoreFoundation                      0x00007fff47fd6cd7 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x00007fff47fd6401 __CFRunLoopRun + 2289
	14  CoreFoundation                      0x00007fff47fd58be CFRunLoopRunSpecific + 455
	15  Foundation                          0x00007fff4a2398ef -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 280
	16  Foundation                          0x00007fff4a2397c4 -[NSRunLoop(NSRunLoop) run] + 76
	17  shuffle                             0x0000000108a31222 shuffle + 8738
	18  libdyld.dylib                       0x00007fff73f0a3d5 start + 1
	19  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by nuthatch** [comment]
This is, of course, my fault for trying to play an empty file. But, fyi. Thank you Jeff!

**Comment by hyperjeff** [comment]
Finally make it at least skip over empty files instead of core dumping on you like that.
