### ISSUE TITLE
Display is unreadable in non light mode terminal window

### ISSUE THREAD

**Issue by woolie** [hyperjeff/shuffle#3]
White text on white background is a bit of a problem:

<img width="849" alt="Screen Shot 2019-07-22 at 12 39 52 PM" src="https://user-images.githubusercontent.com/62043/61660026-d242e680-ac7d-11e9-885e-94651c4eede4.png">

**Comment by hyperjeff** [comment]
Have you given the "-i" flag a try? I think I put it in there when you mentioned it a while ago, but I've clearly been bad about checking the issues here on github. (I need to set my prefs so I get emails about new issues...)

![Screen Shot 2019-10-01 at 12 30 15 AM](https://user-images.githubusercontent.com/64038/65936613-c2185780-e3e2-11e9-88b3-ad36830154c5.png)

**Comment by woolie** [comment]
Jeff! You are awesome.
