### ISSUE TITLE
Crashes on keypress

### ISSUE THREAD

**Issue by logaan** [hyperjeff/shuffle#6]
Starting the app with `shuffle -a ~/Music/GirlTalk/` if I press either the right arrow key or `{` the app will quit with no error message.

Hitting `tab` shows:

```


  current ⟶   04 - Girl Talk - Jump on Stage.mp3


```

Shift tab shows nothing.

All other keys appear to work correctly.

Restarting the app always plays the same track from the middle of the album.

**Comment by hyperjeff** [comment]
I completely missed this, but I believe the problem has been fixed. Let me know if I'm wrong about it, but for now I'll close this.
